
const props = {
	'frameworks': {
		'static': {
			name: 'HTML Statis',
			price: 100000,
			title: "Website Full Client yang hanya menyediakan konten. Cocok untuk pembuatan CV dan Landing Page",
			group: 'Web',
			duration: 7,
		},
		'ci': {
			name: 'CodeIgniter',
			title: "Website PHP konvensional menggunakan CodeIgniter yang simpel digunakan. Cocok untuk pembuatan website bisnis dengan model CMS",
			price: 200000,
			group: 'Web',
			duration: 14,
		},
		'express': {
			name: 'Express',
			title: "Website modern, MERN stack. Cocok untuk pembuatan website interaktif dengan model PWA",
			price: 400000,
			group: 'Web',
			duration: 14,
		},
		'laravel': {
			name: 'Laravel',
			title: "Website modern, MERN stack. Cocok untuk pembuatan website interaktif dengan model PWA",
			price: 600000,
			group: 'Web',
			duration: 21,
		},
		'pyqt': {
			name: 'Python (Qt)',
			title: "Aplikasi Desktop Sederhana menggunakan bahasa Python yang simpel",
			price: 150000,
			group: 'Desktop',
			duration: 7,
		},
		'javafx': {
			name: 'Java (JavaFX)',
			title: "Aplikasi Desktop untuk manajemen data kompleks berbasis OOP dari Java",
			price: 250000,
			group: 'Desktop',
			duration: 14,
		},
		'electron': {
			name: 'NodeJS (Electron)',
			title: "Aplikasi Desktop berbasis Teknologi Web (HTML/CSS/JS) untuk desain fleksibel",
			price: 300000,
			group: 'Desktop',
			duration: 14,
		},
		'pwa': {
			name: 'PWA',
			title: "",
			price: 100000,
			group: 'Mobile',
			duration: 7,
		},
		'android': {
			name: 'Android Native',
			title: "Aplikasi Android Native untuk ukuran aplikasi apapun",
			price: 200000,
			group: 'Mobile',
			duration: 14,
		},
		'ionic': {
			name: 'Ionic React',
			title: "Aplikasi Mobile (Android/iOS) menggunakan teknologi React Native",
			price: 300000,
			group: 'Mobile',
			duration: 21,
		},
		'python': {
			name: 'Python',
			title: "Aplikasi Mobile (Android/iOS) menggunakan teknologi React Native",
			price: 150000,
			group: 'Computing',
			duration: 7,
		},
		'node': {
			name: 'NodeJS',
			title: "Aplikasi Mobile (Android/iOS) menggunakan teknologi React Native",
			price: 300000,
			group: 'Computing',
			duration: 14,
		},
		'cpp': {
			name: 'C++',
			title: "Aplikasi Mobile (Android/iOS) menggunakan teknologi React Native",
			price: 500000,
			group: 'Computing',
			duration: 14,
		},
	},
	'database': {
		'none': {
			name: "Tanpa Database",
			title: "Software tanpa ada data masuk maupun keluar",
			price: 0,
			duration: 0
		},
		'mini': {
			name: "Mini",
			title: "Database untuk mengumpulkan data sederhana dan autentikasi admin saja",
			price: 100000,
			duration: 3,
		},
		'regular': {
			name: "Regular",
			title: "Database ukuran sedang untuk autentikasi admin dan pengguna",
			price: 200000,
			duration: 7,
		},
		'complex': {
			name: "Kompleks",
			title: "Database kompleks menampung berbagai jenis user dan konten",
			price: 500000,
			duration: 14,
		},
		'mega': {
			name: "Forensik",
			title: "Database sangat kompleks menyediakan analisa statis, laporan dan fitur ekspor pada",
			price: 1000000,
			duration: 21,
		},
	},
	'media': {
		'pamflet': {
			name: "Pamflet",
			title: "Desain Grafis untuk Poster, Pamflet atau Banner",
			group: 'Grafis',
			volume: 'Per Desain',
			price: 5,
			priceVolume: 10,
			duration: 2,
			durationVolume: 1,
		},
		'infographic': {
			name: "Infografis",
			title: "Desain grafis yang memuat banyak info termasuk infografis dan pamflet skripsi maupun penelitian",
			group: 'Grafis',
			volume: 'Per Desain',
			price: 10,
			priceVolume: 15,
			duration: 2,
			durationVolume: 2,
		},
		'logo': {
			name: "Logo",
			title: "Logo atau Desain Brand untuk berbagai keperluan",
			group: 'Grafis',
			volume: 'Per Logo',
			price: 30,
			priceVolume: 20,
			duration: 4,
			durationVolume: 2,
		},
		'powerpoint': {
			name: "Powerpoint",
			title: "Media Pembelajaran berbasis Powerpoint",
			group: 'Media',
			volume: 'Per 15 slide',
			price: 10,
			priceVolume: 20,
			duration: 3,
			durationVolume: 3,
		},
		'flash': {
			name: "Flash",
			title: "Media Pembelajaran berbasis Flash",
			group: 'Media',
			volume: 'Per 300 frame',
			price: 100,
			priceVolume: 50,
			duration: 7,
			durationVolume: 7,
		},
		'construct': {
			name: "Construct",
			title: "Media Pembelajaran atau Permainan berbasis Construct 2",
			group: 'Media',
			volume: 'Per level desain',
			price: 200,
			priceVolume: 100,
			duration: 7,
			durationVolume: 7,
		},
		'unity': {
			name: "Unity",
			title: "Media Permainan berbasis Unity",
			group: 'Media',
			volume: 'Per level desain',
			price: 300,
			priceVolume: 200,
			duration: 14,
			durationVolume: 7,
		},
		'video': {
			name: "Video Editing",
			title: "Potong dan Gabung video mentahan menjadi satu",
			group: 'Video',
			volume: 'Per 5 menit',
			price: 40,
			priceVolume: 10,
			duration: 6,
			durationVolume: 3,
		},
		'motion': {
			name: "Video Motion",
			title: "Video dengan elemen geometris bergerak sebagai bahan utama",
			group: 'Video',
			volume: 'Per 30 detik',
			price: 200,
			priceVolume: 50,
			duration: 10,
			durationVolume: 2,
		},
		'2d': {
			name: "Animasi Grafis",
			title: "Video dengan elemen dinamis termasuk karakter, bergerak sebagai bahan utama",
			group: 'Video',
			volume: 'Per 15 detik',
			price: 300,
			priceVolume: 50,
			duration: 21,
			durationVolume: 3,
		},
		'3d': {
			name: "Animasi 3D",
			title: "Video dengan elemen 3D sebagai bahan utama",
			group: 'Video',
			volume: 'Per 15 detik',
			price: 500,
			priceVolume: 50,
			duration: 21,
			durationVolume: 5,
		},
	}
}

export default props;