
const props = {
	'frameworks': {
		'bootstrap': {
			name: 'Bootstrap',
			price: 100000,
			title: "Website konvensional berbasis Bootstrap",
			group: 'Web',
			duration: 7,
		},
		'react': {
			name: 'React',
			price: 150000,
			title: "Website interaktif berbasis ekosistem React",
			group: 'Web',
			duration: 10,
		},
		'ci': {
			name: 'CodeIgniter',
			title: "Server konvensional berbasis PHP CodeIgniter",
			price: 200000,
			group: 'Server',
			duration: 14,
		},
		'express': {
			name: 'Express',
			title: "Server modern berbasis Node.JS Express",
			price: 300000,
			group: 'Server',
			duration: 14,
		},
		'laravel': {
			name: 'Laravel',
			title: "Server kompleks berbasis PHP Laravel",
			price: 500000,
			group: 'Server',
			duration: 21,
		},
		'pyqt': {
			name: 'Python (Qt)',
			title: "Aplikasi Desktop sederhana berbasis Qt + Python",
			price: 150000,
			group: 'Desktop',
			duration: 7,
		},
		'electron': {
			name: 'NodeJS (Electron)',
			title: "Aplikasi Desktop interaktif berbasis Teknologi Web",
			price: 200000,
			group: 'Desktop',
			duration: 14,
		},
		'javafx': {
			name: 'Java (JavaFX)',
			title: "Aplikasi Desktop kompleks berbasis OOP dari Java",
			price: 300000,
			group: 'Desktop',
			duration: 14,
		},
		'pwa': {
			name: 'PWA',
			title: "Website didalam Aplikasi Mobile",
			price: 100000,
			group: 'Mobile',
			duration: 7,
		},
		'flutter': {
			name: 'Flutter',
			title: "Aplikasi Mobile modern berbasis Flutter dari Google",
			price: 200000,
			group: 'Mobile',
			duration: 14,
		},
		'ionic': {
			name: 'Ionic React',
			title: "Aplikasi Mobile interaktif berbasis Ionic + React Native",
			price: 200000,
			group: 'Mobile',
			duration: 14,
		},
		'android': {
			name: 'Android',
			title: "Aplikasi Android Native berbasis Android Studio",
			price: 400000,
			group: 'Mobile',
			duration: 21,
		},
		'python': {
			name: 'Python',
			title: "Aplikasi komputasi untuk A.I.",
			price: 200000,
			group: 'Computing',
			duration: 7,
		},
		'node': {
			name: 'NodeJS',
			title: "Aplikasi komputasi untuk microservice dan cloud-computing",
			price: 300000,
			group: 'Computing',
			duration: 14,
		},
		'cpp': {
			name: 'C++',
			title: "Aplikasi komputasi dengan performa tinggi",
			price: 400000,
			group: 'Computing',
			duration: 14,
		},
		'manual': {
			name: 'Manual PDF',
			title: "Dokumentasi dan Buku Manual",
			price: 100000,
			group: 'Integration',
			duration: 14,
		},
		'rest': {
			name: 'REST API',
			title: "Standar REST API untuk konsumen publik",
			price: 200000,
			group: 'Integration',
			duration: 14,
		},
		'media': {
			name: 'Media Processing',
			title: "Proses Pengolahan Media untuk optimasi data dan penyimpanan",
			price: 300000,
			group: 'Integration',
			duration: 14,
		},
		'graphql': {
			name: 'GraphQL Endpoint',
			title: "GraphQL server untuk konsumen publik",
			price: 400000,
			group: 'Integration',
			duration: 21,
		},
		'livechat': {
			name: 'Live Chat',
			title: "1-in-1 realtime chat antar user",
			price: 500000,
			group: 'Integration',
			duration: 21,
		},
	},
	'database': {
		'none': {
			name: "Tanpa Database",
			title: "Software tanpa ada data masuk maupun keluar",
			price: 0,
			duration: 0
		},
		'mini': {
			name: "Mini",
			title: "Database untuk mengumpulkan data sederhana dan autentikasi admin saja",
			price: 100000,
			duration: 3,
		},
		'regular': {
			name: "Regular",
			title: "Database ukuran sedang untuk autentikasi admin dan pengguna",
			price: 200000,
			duration: 7,
		},
		'complex': {
			name: "Kompleks",
			title: "Database kompleks menampung berbagai jenis user dan konten",
			price: 500000,
			duration: 14,
		},
		'mega': {
			name: "Forensik",
			title: "Database sangat kompleks menyediakan analisa statis, laporan, fitur impor/ekspor dan fitur tambahan lainnya",
			price: 1000000,
			duration: 21,
		},
	},
	'media': {
		'flyer': {
			name: "Flyer",
			title: "Desain Grafis untuk Poster, Pamflet, Banner dan selebaran lainnya",
			group: 'Grafis',
			volume: '1 desain',
			price: 10000,
			priceVolume: 10000,
			duration: 1,
			durationVolume: 2,
		},
		'infographic': {
			name: "Infografis",
			title: "Desain grafis yang memuat banyak info termasuk CV, infografis dan poster skripsi maupun penelitian",
			group: 'Grafis',
			volume: '1 desain',
			price: 10000,
			priceVolume: 15000,
			duration: 2,
			durationVolume: 3,
		},
		'branding': {
			name: "Branding",
			title: "Desain Brand termasuk Logo, Produk, Stiker dan Kartu Nama",
			group: 'Grafis',
			volume: '1 desain',
			price: 10000,
			priceVolume: 5000,
			duration: 3,
			durationVolume: 2,
		},
		'feed': {
			name: "Instagram",
			title: "Desain untuk Instagram Feed",
			group: 'Grafis',
			volume: '1 petak',
			price: 20000,
			priceVolume: 5000,
			duration: 4,
			durationVolume: 1,
		},
		'humanoid2D': {
			name: "Karakter 2D",
			title: "Karakter Dinamis, Humanoid 2D",
			group: 'Props',
			volume: '1 desain karakter',
			price: 60000,
			priceVolume: 40000,
			duration: 5,
			durationVolume: 7,
		},
		'humanoid3D': {
			name: "Karakter 3D",
			title: "Karakter Dinamis, Humanoid 3D",
			group: 'Props',
			volume: '1 desain karakter',
			price: 150000,
			priceVolume: 100000,
			duration: 10,
			durationVolume: 7,
		},
		'props2D': {
			name: "Props 2D",
			title: "Desain grafis mentah untuk elemen media 2D",
			group: 'Props',
			volume: '1 jenis prop',
			price: 40000,
			priceVolume: 20000,
			duration: 3,
			durationVolume: 5,
		},
		'props3D': {
			name: "Props 3D",
			title: "Desain grafis mentah untuk elemen media 3D",
			group: 'Props',
			volume: '1 jenis prop',
			price: 100000,
			priceVolume: 50000,
			duration: 5,
			durationVolume: 5,
		},
		'audioSFX': {
			name: "Audio SFX",
			title: "Sound Effect untuk elemen media tertentu",
			group: 'Props',
			volume: '1 jenis FX',
			price: 50000,
			priceVolume: 10000,
			duration: 5,
			durationVolume: 3,
		},
		'audioMusic': {
			name: "Background Music",
			title: "Background Music untuk elemen media tertentu",
			group: 'Props',
			volume: '1 musik',
			price: 150000,
			priceVolume: 40000,
			duration: 5,
			durationVolume: 7,
		},
		'powerpoint': {
			name: "Powerpoint",
			title: "Media Pembelajaran berbasis Powerpoint",
			group: 'Media',
			volume: '10 slide',
			price: 20000,
			priceVolume: 10000,
			duration: 7,
			durationVolume: 2,
		},
		'flash': {
			name: "Flash",
			title: "Media Pembelajaran berbasis Flash",
			group: 'Media',
			volume: '100 frame',
			price: 100000,
			priceVolume: 25000,
			duration: 15,
			durationVolume: 5,
		},
		'construct': {
			name: "Arcade Games",
			title: "Permainan Arcade berbasis Construct 2",
			group: 'Media',
			volume: '1 level desain',
			price: 200000,
			priceVolume: 50000,
			duration: 14,
			durationVolume: 7,
		},
		'unity': {
			name: "Unity Games",
			title: "Permainan berbasis Unity",
			group: 'Media',
			volume: '1 level desain',
			price: 300000,
			priceVolume: 100000,
			duration: 21,
			durationVolume: 7,
		},
		'video': {
			name: "Video Editing",
			title: "Potong dan Gabung video mentahan menjadi satu",
			group: 'Video',
			volume: '5 menit',
			price: 50000,
			priceVolume: 10000,
			duration: 5,
			durationVolume: 1,
		},
		'compositing': {
			name: "Video Composition",
			title: "Potong gabung video footage dengan animasi grafis",
			group: 'Video',
			volume: '2 menit',
			price: 100000,
			priceVolume: 20000,
			duration: 7,
			durationVolume: 3,
		},
		'motion': {
			name: "Video Motion",
			title: "Video dengan elemen geometris bergerak sebagai bahan utama",
			group: 'Video',
			volume: '30 detik',
			price: 200000,
			priceVolume: 50000,
			duration: 14,
			durationVolume: 2,
		},
		'2d': {
			name: "Animasi Grafis",
			title: "Video dengan elemen dinamis bergerak sebagai bahan utama",
			group: 'Video',
			volume: '15 detik',
			price: 300000,
			priceVolume: 50000,
			duration: 21,
			durationVolume: 3,
		},
		'3d': {
			name: "Animasi 3D",
			title: "Video dengan elemen 3D sebagai bahan utama",
			group: 'Video',
			volume: '15 detik',
			price: 500000,
			priceVolume: 50000,
			duration: 21,
			durationVolume: 5,
		},
	}
}

export default props;