
const props = {
	'frameworks': {
		'static': {
			name: 'HTML Statis',
			price: 100000,
			title: "Website Full HTML/CSS/JS cocok untuk halaman profil dan CV.",
			group: 'Web',
			duration: 7,
		},
		'ci': {
			name: 'CodeIgniter',
			title: "Website dengan backend CodeIgniter PHP cocok untuk website bisnis menengah.",
			price: 200000,
			group: 'Web',
			duration: 14,
		},
		'express': {
			name: 'Express',
			title: "Website dengan backend Node.JS cocok untuk website bisnis dengan interaksi kompleks.",
			price: 400000,
			group: 'Web',
			duration: 14,
		},
		'laravel': {
			name: 'Laravel',
			title: "Website dengan backend Laravel PHP cocok untuk website bisnis dengan integrasi tinggi.",
			price: 600000,
			group: 'Web',
			duration: 21,
		},
		'pyqt': {
			name: 'Python (Qt)',
			title: "Aplikasi Desktop Sederhana menggunakan bahasa Qt + Python.",
			price: 150000,
			group: 'Desktop',
			duration: 7,
		},
		'javafx': {
			name: 'Java (JavaFX)',
			title: "Aplikasi Desktop untuk manajemen data kompleks berbasis OOP dari Java",
			price: 250000,
			group: 'Desktop',
			duration: 14,
		},
		'electron': {
			name: 'NodeJS (Electron)',
			title: "Aplikasi Desktop berbasis Teknologi Web (HTML/CSS/JS)",
			price: 300000,
			group: 'Desktop',
			duration: 14,
		},
		'pwa': {
			name: 'PWA',
			title: "Aplikasi Mobile berbasis Website",
			price: 100000,
			group: 'Mobile',
			duration: 7,
		},
		'android': {
			name: 'Android',
			title: "Aplikasi Android berbasis Android Studio (Java/Kotlin)",
			price: 200000,
			group: 'Mobile',
			duration: 14,
		},
		'ionic': {
			name: 'Ionic React',
			title: "Aplikasi Mobile (Android/iOS) menggunakan teknologi React Native",
			price: 300000,
			group: 'Mobile',
			duration: 21,
		},
		'python': {
			name: 'Python',
			title: "Aplikasi komputasi untuk data mining",
			price: 150000,
			group: 'Computing',
			duration: 7,
		},
		'node': {
			name: 'NodeJS',
			title: "Aplikasi komputasi untuk cloud-computing",
			price: 300000,
			group: 'Computing',
			duration: 14,
		},
		'cpp': {
			name: 'C++',
			title: "Aplikasi komputasi dengan performa tinggi",
			price: 500000,
			group: 'Computing',
			duration: 14,
		},
	},
	'database': {
		'none': {
			name: "Tanpa Database",
			title: "Software tanpa ada data masuk maupun keluar",
			price: 0,
			duration: 0
		},
		'mini': {
			name: "Mini",
			title: "Database untuk mengumpulkan data sederhana dan autentikasi admin saja",
			price: 100000,
			duration: 3,
		},
		'regular': {
			name: "Regular",
			title: "Database ukuran sedang untuk autentikasi admin dan pengguna",
			price: 200000,
			duration: 7,
		},
		'complex': {
			name: "Kompleks",
			title: "Database kompleks menampung berbagai jenis user dan konten",
			price: 500000,
			duration: 14,
		},
		'mega': {
			name: "Forensik",
			title: "Database sangat kompleks menyediakan analisa statis, laporan dan fitur impor/ekspor",
			price: 1000000,
			duration: 21,
		},
	},
	'media': {
		'flyer': {
			name: "Flyer",
			title: "Desain Grafis untuk Poster, Pamflet atau Banner",
			group: 'Grafis',
			volume: '1 desain',
			price: 5000,
			priceVolume: 10000,
			duration: 2,
			durationVolume: 1,
		},
		'infographic': {
			name: "Infografis",
			title: "Desain grafis yang memuat banyak info termasuk CV, infografis dan poster skripsi maupun penelitian",
			group: 'Grafis',
			volume: '1 desain',
			price: 15000,
			priceVolume: 15000,
			duration: 2,
			durationVolume: 2,
		},
		'logo': {
			name: "Logo",
			title: "Logo atau Desain Brand untuk berbagai keperluan",
			group: 'Grafis',
			volume: '1 logo',
			price: 30000,
			priceVolume: 20000,
			duration: 4,
			durationVolume: 2,
		},
		'powerpoint': {
			name: "Powerpoint",
			title: "Media Pembelajaran berbasis Powerpoint",
			group: 'Media',
			volume: '15 slide',
			price: 10000,
			priceVolume: 20000,
			duration: 3,
			durationVolume: 3,
		},
		'flash': {
			name: "Flash",
			title: "Media Pembelajaran berbasis Flash",
			group: 'Media',
			volume: '300 frame',
			price: 100000,
			priceVolume: 50000,
			duration: 7,
			durationVolume: 7,
		},
		'construct': {
			name: "Construct",
			title: "Media Pembelajaran atau Permainan berbasis Construct 2",
			group: 'Media',
			volume: '1 level desain',
			price: 200000,
			priceVolume: 100000,
			duration: 7,
			durationVolume: 7,
		},
		'unity': {
			name: "Unity",
			title: "Media Permainan berbasis Unity",
			group: 'Media',
			volume: '1 level desain',
			price: 300000,
			priceVolume: 200000,
			duration: 14,
			durationVolume: 7,
		},
		'video': {
			name: "Video Editing",
			title: "Potong dan Gabung video mentahan menjadi satu",
			group: 'Video',
			volume: '5 menit',
			price: 40000,
			priceVolume: 10000,
			duration: 6,
			durationVolume: 3,
		},
		'motion': {
			name: "Video Motion",
			title: "Video dengan elemen geometris bergerak sebagai bahan utama",
			group: 'Video',
			volume: '30 detik',
			price: 200000,
			priceVolume: 50000,
			duration: 10,
			durationVolume: 2,
		},
		'2d': {
			name: "Animasi Grafis",
			title: "Video dengan elemen dinamis termasuk karakter, bergerak sebagai bahan utama",
			group: 'Video',
			volume: '15 detik',
			price: 300000,
			priceVolume: 50000,
			duration: 21,
			durationVolume: 3,
		},
		'3d': {
			name: "Animasi 3D",
			title: "Video dengan elemen 3D sebagai bahan utama",
			group: 'Video',
			volume: '15 detik',
			price: 500000,
			priceVolume: 50000,
			duration: 21,
			durationVolume: 5,
		},
	}
}

export default props;